export const FALLBACK_PRODUCTS = [
  {
    _id: '1',
    name: 'Acti Rooti - Siêu Kích Rễ Cực Mạnh (500ml)',
    slug: 'acti-rooti-sieu-kich-re-cuc-manh',
    category: 'Kích rễ',
    price: 120000,
    originalPrice: 150000,
    description: 'Acti Rooti là chế phẩm kích rễ thế hệ mới, giúp bộ rễ phát triển cực mạnh, giải độc phèn, ngộ độc hữu cơ.',
    short_desc: 'Kích rễ cực mạnh, phục hồi bộ rễ sau thu hoạch.',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=800&auto=format&fit=crop'],
    stock: 500,
    soldCount: 0,
    rating: 0,
    numReviews: 0,
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  {
    _id: '2',
    name: 'Acti Flora - Ra Hoa Đồng Loạt, Chống Rụng Trái (500ml)',
    slug: 'acti-flora-ra-hoa-dong-loat-chong-rung-trai',
    category: 'Phân bón lá',
    price: 135000,
    originalPrice: 165000,
    description: 'Acti Flora cung cấp Amino Acid và vi lượng giúp cây ra hoa đồng loạt, tăng tỷ lệ đậu trái.',
    short_desc: 'Đậu trái cực mạnh, chống rụng trái non.',
    images: ['https://images.unsplash.com/photo-1592982537447-7440770cbfc9?q=80&w=800&auto=format&fit=crop'],
    stock: 300,
    soldCount: 0,
    rating: 0,
    numReviews: 0,
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  {
    _id: '3',
    name: 'Nemano - Chế Phẩm Sinh Học Đặc Trị Tuyến Trùng (1L)',
    slug: 'nemano-dac-tri-tuyen-trung-sinh-hoc',
    category: 'Tuyến trùng',
    price: 250000,
    originalPrice: 300000,
    description: 'Nemano tiêu diệt tuyến trùng gây hại rễ bằng cơ chế sinh học.',
    short_desc: 'Tiêu diệt tuyến trùng rễ, bảo vệ vườn cây.',
    images: ['https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop'],
    stock: 200,
    soldCount: 0,
    rating: 0,
    numReviews: 0,
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  {
    _id: '4',
    name: 'Combo Phục Hồi Vườn 3 Bước Sau Thu Hoạch',
    slug: 'combo-phuc-hoi-vuon-3-buoc',
    category: 'Combo tiết kiệm',
    price: 450000,
    originalPrice: 520000,
    description: 'Bộ combo gồm Acti Rooti + Nemano + Phân bón lá.',
    short_desc: 'Bộ 3 phục hồi, nuôi cây khỏe mạnh.',
    images: ['https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=800&auto=format&fit=crop'],
    stock: 100,
    soldCount: 0,
    rating: 0,
    numReviews: 0,
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  {
    _id: '5',
    name: 'Combo Siêu Đậu Trái & Dưỡng Trái Non',
    slug: 'combo-sieu-dau-trai-duong-trai-non',
    category: 'Combo tiết kiệm',
    price: 280000,
    originalPrice: 350000,
    description: 'Bộ đôi Acti Flora và Bo-Canxi giúp bông sáng, đậu trái cực mạnh.',
    short_desc: 'Sáng bông, đậu trái, chống rụng.',
    images: ['https://images.unsplash.com/photo-1595113316349-9fa404641847?q=80&w=800&auto=format&fit=crop'],
    stock: 150,
    soldCount: 0,
    rating: 0,
    numReviews: 0,
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  }
];
