export const FALLBACK_PRODUCTS = [
  { 
    _id: '1', 
    name: "Phân bón Acti Rooti", 
    price: 180000, 
    originalPrice: 220000,
    images: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=800&auto=format&fit=crop"], 
    slug: "rooti-4339", 
    category: "Phân bón", 
    rating: 5, 
    numReviews: 120,
    soldCount: 1542,
    stock: 99,
    description: "Acti Rooti là giải pháp kích rễ thế hệ mới, giúp bộ rễ phát triển cực mạnh, tăng khả năng hấp thụ dinh dưỡng và phục hồi cây sau thu hoạch.",
    benefits: ["Kích rễ cực mạnh", "Phục hồi cây suy yếu", "Tăng sức đề kháng"],
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  { 
    _id: '2', 
    name: "Nemano Tuyến Trùng", 
    price: 180000, 
    originalPrice: 250000,
    images: ["https://images.unsplash.com/photo-1592982537447-7440770cbfc9?q=80&w=800&auto=format&fit=crop"], 
    slug: "phan-bon-phong-ngua-tuyen-trung-nemano-9989", 
    category: "Phân bón", 
    rating: 5, 
    numReviews: 85,
    soldCount: 890,
    stock: 50,
    description: "Nemano giúp tiêu diệt và phòng ngừa tuyến trùng gây hại rễ, bảo vệ vườn cây khỏi vàng lá thối rễ.",
    benefits: ["Tiêu diệt tuyến trùng", "Bảo vệ bộ rễ", "An toàn sinh học"],
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  { 
    _id: '3', 
    name: "NPK Sinh Học", 
    price: 150000, 
    originalPrice: 180000,
    images: ["https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop"], 
    slug: "phan-bon-npk-sinh-hoc", 
    category: "Phân bón", 
    rating: 5, 
    numReviews: 64,
    soldCount: 420,
    stock: 120,
    description: "NPK Sinh học cung cấp đầy đủ đa trung vi lượng giúp cây phát triển cân đối, tăng năng suất.",
    benefits: ["Cân bằng dinh dưỡng", "Tăng năng suất", "Đất tơi xốp"],
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  },
  { 
    _id: '4', 
    name: "Siêu Lân Đỏ Kích Rễ", 
    price: 220000, 
    originalPrice: 280000,
    images: ["https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=800&auto=format&fit=crop"], 
    slug: "sieu-lan-do-kich-re", 
    category: "Kích rễ", 
    rating: 5, 
    numReviews: 92,
    soldCount: 1105,
    stock: 8,
    description: "Siêu Lân Đỏ kích thích mầm hoa, tạo mầm nhanh, kích rễ cực mạnh cho cây trồng.",
    benefits: ["Kích rễ nhanh", "Tạo mầm hoa", "Chống nghẹt rễ"],
    seller: { role: 'admin', vendorInfo: { storeName: 'Phân Bón Giá Tốt', isApproved: true } }
  }
];
